### ISSUE TITLE
verify the url?

### ISSUE THREAD

**Issue by joshendriks** [Jordi1990/aioaquacell#1]
Great stuff I was looking for someyhing like this!
But before I fill in my password

How can I verify  https://y7xyrocicl.execute-api.eu-west-1.amazonaws.com is owned by aquacell? Or how did youget this info?

**Comment by Jordi1990** [comment]
All the used URLs and IDs are retrieved from the android mobile app. 

I'm not aware of any endpoint on this rest API to be able to identify it without authentication.

You could verify it by decompiling the APK and check the res\raw\amplifyconfiguration.json file.

**Comment by joshendriks** [comment]
Ok, thanks a lot! Maybe add this info to the REAME.md? I would be happy to create a PR for that.
