### ISSUE TITLE
Integration with Home Assistant?

### ISSUE THREAD

**Issue by rvdlinden** [Jordi1990/aioaquacell#2]
I'm using Home Assistant for a while and one of the devices still not I there is the AquaCell. 

I saw this code and was also able to debug the app using an AVD for Android together with Burpsuite, but I'm not good enough in python programming. 

Do you think this code could be integrated into Home Assistant somehow?

**Comment by Jordi1990** [comment]
There is an open pull request to integrate this into home assistant.

home-assistant/core#117117
